import { Vollkorn } from "next/font/google";
import "./globals.css";

const vollkorn = Vollkorn({
  weight: ["400", "500", "600", "700"],
  subsets: ["cyrillic"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${vollkorn.className} antialiased`}>{children}</body>
    </html>
  );
}
