import { Vollkorn, Noto_Sans } from "next/font/google";
import "./globals.css";

const vollkorn = Vollkorn({
  weight: ["400", "500", "600", "700"],
  subsets: ["cyrillic"],
  display: "swap",
});

const notoSans = Noto_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["cyrillic"],
  display: "swap",
  variable: "--font-noto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${vollkorn.className} ${notoSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
